### ISSUE TITLE
where can I talk one to one ?

### ISSUE THREAD

**Issue by jsroyal** [obahareth/ama#1]

**Comment by obahareth** [comment]
Hey @jsroyal, if you're asking about talking to me one to one, you can find many ways to contact me on [my website](https://omar.engineer) including email, Twitter, Telegram, and so on.

If you're asking about tools for on on one calling with others, I like [Google Hangouts](https://hangouts.google.com) for general calls, [Google Meet](https://meet.google.com) or [Zoom](https://zoom.us) for meetings, and [Google Duo](https://duo.google.com) for facetime-like personal calls quite a bit.

I hope I managed to answer your question.

**Comment by jsroyal** [comment]
:
